# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dbexpression.com

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GOOGLE_ANALYTICS_ID: G-5E8SMEDZT3
  DOCS_URL: https://dbexpression-docs.azurewebsites.net/

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Create env file
        run: |
          touch .env.local
          echo NEXT_PUBLIC_GOOGLE_ANALYTICS_ID=$GOOGLE_ANALYTICS_ID >> .env.local
          echo DOCS_URL=$DOCS_URL >> .env.local

      - name: npm install, build, and test
        run: |
          npm install
          npm run build

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dbexpression'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .